spring.application.name=order-service
server.port=8080

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=postgres
spring.datasource.password=Root@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.jwtSecret=2cd59c3c2cf0c100c5f319b4a5113419d726a3abe5858cb15f5abc4e5bcc41e0
app.jwtExpiration=86400000